export const NODE_TYPES = {
  PROJECT: 'PROJECT',
  DATABASE: 'DATABASE',
  API: 'API',
  HOSTING: 'HOSTING',
  REPOSITORY: 'REPOSITORY',
  DOCUMENTATION: 'DOCUMENTATION'
}

export const NODE_COLORS = {
  PROJECT: '#4CAF50',
  DATABASE: '#2196F3',
  API: '#FF9800',
  HOSTING: '#9C27B0',
  REPOSITORY: '#607D8B',
  DOCUMENTATION: '#795548'
}

export const NODE_ICONS = {
  PROJECT: '📂',
  DATABASE: '💾',
  API: '🔌',
  HOSTING: '☁️',
  REPOSITORY: '📦',
  DOCUMENTATION: '📚'
}
